<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1bjFFxC\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1bjFFxC/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container1bjFFxC.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container1bjFFxC\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container1bjFFxC\App_KernelProdContainer([
    'container.build_hash' => '1bjFFxC',
    'container.build_id' => '84a716e4',
    'container.build_time' => 1583851008,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1bjFFxC');
