<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAl1H6Ax\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAl1H6Ax/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAl1H6Ax.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAl1H6Ax\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAl1H6Ax\App_KernelDevDebugContainer([
    'container.build_hash' => 'Al1H6Ax',
    'container.build_id' => 'e4a2f629',
    'container.build_time' => 1587647466,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAl1H6Ax');
