<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHZddxnR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHZddxnR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHZddxnR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHZddxnR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHZddxnR\App_KernelDevDebugContainer([
    'container.build_hash' => 'HZddxnR',
    'container.build_id' => '2e4693e0',
    'container.build_time' => 1588264478,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHZddxnR');
