<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJFNUIsX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJFNUIsX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJFNUIsX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJFNUIsX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJFNUIsX\App_KernelDevDebugContainer([
    'container.build_hash' => 'JFNUIsX',
    'container.build_id' => 'a6c3f1e1',
    'container.build_time' => 1587896594,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJFNUIsX');
